version: '3'
services:
  parent:
    image: "overlaytoken:0.1"
    volumes:
      - "./substrate-overlay-token/target/release/substrate-overlay-token:/usr/local/bin/substrate-overlay-token"
      - "./substrate-overlay-token/docker/parent.sh:/parent.sh"
    entrypoint: bash
    command: parent.sh
  child:
    image: "overlaytoken:0.1"
    volumes:
      - "./substrate-overlay-token/target/release/substrate-overlay-token:/usr/local/bin/substrate-overlay-token"
      - "./substrate-overlay-token/docker/child.sh:/child.sh"
    entrypoint: bash
    command: child.sh
  nginx:
    image: "nginx"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/letsencrypt/live/{YOUR_DOMAIN}/fullchain.pem:/etc/letsencrypt/live/{YOUR_DOMAIN}/fullchain.pem"
      - "/etc/letsencrypt/live/{YOUR_DOMAIN}/privkey.pem:/etc/letsencrypt/live/{YOUR_DOMAIN}/privkey.pem"
    ports:
      - "9944:9944"
      - "9945:9945"
  bridge:
    image: "node"
    volumes:
      - "./substrate-overlay-token-bridge:/app"
    environment:
      PARENT: "wss://{YOUR_DOMAIN}:9944"
      CHILD: "wss://{YOUR_DOMAIN}:9945"   
    working_dir: "/app"
    entrypoint: bash
    command: env.sh
  ui-parent:
    image: "node"
    volumes:
      - "./substrate-overlay-token-ui:/app"      
    ports:
      - "8000:8000"
    environment:
      NODE: "wss://{YOUR_DOMAIN}:9944"
    working_dir: "/app"
    entrypoint: bash
    command: env.sh
  ui-child:
    image: "node"
    volumes:
      - "./substrate-overlay-token-ui:/app"
    ports:
      - "8001:8000"
    environment:
      NODE: "wss://{YOUR_DOMAIN}:9945"
    working_dir: "/app"
    entrypoint: bash
    command: env.sh
